name: GLPI
description: |
  Gestion de parc informatique
version: v1.0-dev
category: IT
maintainer: loic.chauvel@ocea-smart-building.fr
license: GPLv3
projectURL: https://hub.docker.com/r/cathode/glpi/
