.catalog:
  name: nextcloud
  version: "0.0.1- 1.0 experimental"
  description: Cloud modulaire open-source

services:

  nextcloud:
    scale: 1
    start_on_create: true

  nextcloud-data:
    scale: 1
    start_on_create: true

  mariadb:
    scale: 1
    start_on_create: true

  mariadb-data:
    scale: 1
    start_on_create: true

