alfresco:
  environment:
    CIFS_ENABLED: 'false'
    FTP_ENABLED: 'false'
  labels:
    io.rancher.sidekicks: alfresco-data
  tty: true
  image: webcenter/rancher-alfresco:v5.1-201605-1
  links:
  - postgres:db
  stdin_open: true
  ports:
  - 1882:8080/tcp
  volumes_from:
    - alfresco-data
alfresco-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: alpine
  volumes:
  - /opt/alfresco/alf_data
  net: none
  command: /bin/true
postgres:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: alfresco
    POSTGRES_PASSWORD: alfresco
    POSTGRES_USER: alfresco
  labels:
    io.rancher.sidekicks: postgres-data
  tty: true
  image: postgres:9.4
  stdin_open: true
  volumes_from:
    - postgres-data
postgres-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: alpine
  volumes:
  - /var/lib/postgresql/data/pgdata
  net: none
  command: /bin/true
