.catalog:
  name: "Alfresco"
  version: "5.1.0 - 1.0 experimental"
  description: "Alfresco Electronic Document Management"
  uuid: alfresco-5.1-201605-1
  minimum_rancher_version: v0.56.0

alfresco:
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

postgres:
  scale: 1
  health_check:
    port: 5432
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 3

postgres-data:
  scale: 1

alfresco-data:
  scale: 1
